on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'eic/generate-meeting-slides branch to run against'
        type: string
        default: 'main'
        required: false

jobs:
  generate-weekly-meeting-slides:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: eic/generate-meeting-slides
        ref: ${{ inputs.branch }}
        path: eic/generate-meeting-slides
    - uses: ./eic/generate-meeting-slides
      with:
        since: "1 week ago"
